Arm 32 & 64 on Debian 8,9 & 10 via docker
Former-commit-id: 3ad5a55a1e5b164c8024bb840ce63f3756c72fb4

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,6 +10,13 @@ matrix:
     os: linux
     dist: xenial
 
+  - name: Arm 32 & 64 on Debian 8,9 & 10 via docker
+    os: linux
+    dist: xenial
+    env:
+    - MULTIARCH_IMAGES="multiarch/debian-debootstrap:arm64-buster multiarch/debian-debootstrap:arm64-jessie multiarch/debian-debootstrap:arm64-stretch multiarch/debian-debootstrap:armhf-buster multiarch/debian-debootstrap:armhf-jessie multiarch/debian-debootstrap:armhf-stretch"
+    - TEST_SCRIPT="debian_prepare && install_w3top"
+
   - name: SystemD on Debian 8 (systemd 215), 9 & 10 (systemd 241) via docker
     os: linux
     dist: xenial
@@ -298,6 +305,29 @@ script:
        docker exec -t "$name" bash -c "echo HOME: \$HOME; source /test-sources.sh; $TEST_SCRIPT && echo 'TEST FINISHED. Checking app health.'"
        wait_for_http http://localhost:${port}
        curl -I http://localhost:${port} || error=1
+
+     done
+   fi
+   echo "ERROR is [$error]"
+   if [[ $error != "none" ]]; then fail; fi
+
+ - |
+   error=none;
+   if [[ "$MULTIARCH_IMAGES" != "" ]]; then
+     cat tests/*.sh > tests/test-sources.sh; chmod +x tests/test-sources.sh
+     time docker run --rm --privileged multiarch/qemu-user-static:register --reset
+     port=15060;
+     for img in $MULTIARCH_IMAGES; do
+       port=$((port+1)); name="multiarch_${port}";
+
+       docker run --privileged -d --name $name -p "$port:5050" "$img" sh -c "while true; do sleep 42; done"
+       docker exec -t $name bash -c "cat /etc/*release"
+       docker exec -t $name bash -c "mkdir -p /etc/init.d"
+
+       docker cp tests/test-sources.sh $name:/test-sources.sh
+       docker exec -t $name bash -c "echo HOME: \$HOME; source /test-sources.sh; $TEST_SCRIPT && echo 'TEST FINISHED. Checking app health.'"
+       wait_for_http http://localhost:$port
+       curl -I http://localhost:$port || error=1
 
      done
    fi
